elasticsearch:
  image: elasticsearch:latest
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    # disable X-Pack
    # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
    #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
    xpack.security.enabled: "false"
    xpack.monitoring.enabled: "false"
    xpack.graph.enabled: "false"
    xpack.watcher.enabled: "false"
    
logstash:
  build: logstash/
  links:
    - elasticsearch:elasticsearch
  volumes:
    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./logstash/pipeline:/usr/share/logstash/pipeline
  ports:
    - "5000:5000"
    
kibana:
  image: kibana
  links:
    - elasticsearch:elasticsearch
  ports:
    - "5601:5601"
  environment:
  - ELASTICSEARCH_URL=http://elasticsearch:9200